# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)

# Keybindinds
## Tabs Configuration
config.bind('J', 'tab-prev')
config.bind('K', 'tab-next')
c.tabs.tabs_are_windows = True

# Theme Customization
c.colors.webpage.darkmode.enabled = True
c.colors.webpage.bg = 'black'

# Search
c.url.default_page ="https://google.com"
c.url.searchengines = {"DEFAULT":"https://google.com/search?q={}"}
c.url.start_pages = "https://google.com"
c.url.searchengines["ghs"] = "https://github.com/search?q={}"
c.url.searchengines["gh"] = "https://github.com/{}"

# Completion Configuration
## Movement
config.bind('<Ctrl-j>', 'completion-item-focus --history next', mode='command')
config.bind('<Ctrl-k>', 'completion-item-focus --history prev', mode='command')
